spring:
  application:
    name: Online_Shopping_Application
    
    #DataBase configuration
  datasource:
    url: jdbc:mysql://localhost:3306/osadb?createDatabaseIfNotExist=true
    username: root
    password: root
    
    #JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
        #SMTP configuration
  mail:
    host: smtp.gmail.com
    username: akhilesh.v2312@gmail.com
    password: ymlq smwd uqpk yvpc   
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
            
       